module = require("../../../dist/Trello/Functions/filterCards");
const testData = require("./filterCards.test.json");

const cases = [
    {
        "cardArray": testData,
        "return": {
            statusText: 'OK',
            data: [
                {
                    id: '60fa41555c017a81ce406486',
                    badges: [Array],
                    checkItemStates: null,
                    closed: false,
                    dueComplete: false,
                    dateLastActivity: '2022-03-02T23:38:40.086Z',
                    desc: '',
                    descData: null,
                    due: null,
                    dueReminder: -1,
                    email: null,
                    idBoard: '60f9a701934112757875ce38',
                    idChecklists: [Array],
                    idList: '6216811a0cd54f0a231dbfa2',
                    idMembers: [],
                    idMembersVoted: [],
                    idShort: 14,
                    idAttachmentCover: null,
                    labels: [],
                    idLabels: [],
                    manualCoverAttachment: false,
                    name: 'Card 1',
                    pos: 436480,
                    shortLink: 'pBCF07FY',
                    shortUrl: 'https://trello.com/c/pBCF07FY',
                    start: '2022-03-02T04:00:00.000Z',
                    subscribed: false,
                    url: 'https://trello.com/c/pBCF07FY/14-card-1',
                    cover: [Array],
                    isTemplate: false,
                    cardRole: null
                },
                {
                    id: '612bfeb4d3b75f6f89c7b20a',
                    badges: [Array],
                    checkItemStates: null,
                    closed: false,
                    dueComplete: false,
                    dateLastActivity: '2022-03-02T23:38:40.095Z',
                    desc: '',
                    descData: null,
                    due: '2022-03-04T03:59:59.000Z',
                    dueReminder: null,
                    email: null,
                    idBoard: '60f9a701934112757875ce38',
                    idChecklists: [],
                    idList: '6216811a0cd54f0a231dbfa2',
                    idMembers: [],
                    idMembersVoted: [],
                    idShort: 287,
                    idAttachmentCover: null,
                    labels: [],
                    idLabels: [],
                    manualCoverAttachment: false,
                    name: 'Card 2',
                    pos: 502016,
                    shortLink: '8iH7WNIq',
                    shortUrl: 'https://trello.com/c/8iH7WNIq',
                    start: '2022-03-02T04:00:00.000Z',
                    subscribed: false,
                    url: 'https://trello.com/c/8iH7WNIq/287-card-2',
                    cover: [Array],
                    isTemplate: false,
                    cardRole: null
                },
                {
                    id: '60fd985ffdce8910d6723cb0',
                    badges: [Array],
                    checkItemStates: null,
                    closed: false,
                    dueComplete: false,
                    dateLastActivity: '2022-03-02T23:38:40.177Z',
                    desc: '',
                    descData: null,
                    due: '1970-01-01T00:00:00.005Z',
                    dueReminder: -1,
                    email: null,
                    idBoard: '60f9a701934112757875ce38',
                    idChecklists: [Array],
                    idList: '6216811a0cd54f0a231dbfa2',
                    idMembers: [],
                    idMembersVoted: [],
                    idShort: 224,
                    idAttachmentCover: null,
                    labels: [],
                    idLabels: [],
                    manualCoverAttachment: false,
                    name: 'Card 3',
                    pos: 567552,
                    shortLink: 'EjXHJMK3',
                    shortUrl: 'https://trello.com/c/EjXHJMK3',
                    start: '2022-02-28T12:00:00.000Z',
                    subscribed: false,
                    url: 'https://trello.com/c/EjXHJMK3/224-card-3',
                    cover: [Array],
                    isTemplate: false,
                    cardRole: null
                },
                {
                    id: '6137c28da3e07f6ba07ff01e',
                    badges: [Array],
                    checkItemStates: null,
                    closed: false,
                    dueComplete: false,
                    dateLastActivity: '2022-03-02T23:38:40.180Z',
                    desc: '',
                    descData: null,
                    due: null,
                    dueReminder: -1,
                    email: null,
                    idBoard: '60f9a701934112757875ce38',
                    idChecklists: [],
                    idList: '6216811a0cd54f0a231dbfa2',
                    idMembers: [],
                    idMembersVoted: [],
                    idShort: 297,
                    idAttachmentCover: null,
                    labels: [],
                    idLabels: [],
                    manualCoverAttachment: false,
                    name: 'Card 4',
                    pos: 633088,
                    shortLink: 'Wc2W7vdT',
                    shortUrl: 'https://trello.com/c/Wc2W7vdT',
                    start: '2022-03-01T12:00:00.000Z',
                    subscribed: false,
                    url: 'https://trello.com/c/Wc2W7vdT/297-card-4',
                    cover: [Array],
                    isTemplate: false,
                    cardRole: null
                },
                {
                    id: '6216813334e8d64b77e547d2',
                    badges: [Array],
                    checkItemStates: null,
                    closed: false,
                    dueComplete: false,
                    dateLastActivity: '2022-03-02T23:38:40.264Z',
                    desc: '',
                    descData: [Array],
                    due: null,
                    dueReminder: -1,
                    email: null,
                    idBoard: '60f9a701934112757875ce38',
                    idChecklists: [],
                    idList: '6216811a0cd54f0a231dbfa2',
                    idMembers: [],
                    idMembersVoted: [],
                    idShort: 301,
                    idAttachmentCover: null,
                    labels: [],
                    idLabels: [],
                    manualCoverAttachment: false,
                    name: 'Card 5',
                    pos: 698624,
                    shortLink: 'XU0BbjYx',
                    shortUrl: 'https://trello.com/c/XU0BbjYx',
                    start: '2022-03-01T12:00:00.000Z',
                    subscribed: false,
                    url: 'https://trello.com/c/XU0BbjYx/301-card-5',
                    cover: [Array],
                    isTemplate: false,
                    cardRole: null
                },
                {
                    id: '621e7d1ef9b99e634a6a5853',
                    badges: [Array],
                    checkItemStates: null,
                    closed: false,
                    dueComplete: false,
                    dateLastActivity: '2022-03-03T21:16:47.732Z',
                    desc: '',
                    descData: [Array],
                    due: null,
                    dueReminder: -1,
                    email: null,
                    idBoard: '60f9a701934112757875ce38',
                    idChecklists: [],
                    idList: '6216811a0cd54f0a231dbfa2',
                    idMembers: [],
                    idMembersVoted: [],
                    idShort: 302,
                    idAttachmentCover: null,
                    labels: [],
                    idLabels: [],
                    manualCoverAttachment: false,
                    name: 'Card 6',
                    pos: 764160,
                    shortLink: '5SdxIKHl',
                    shortUrl: 'https://trello.com/c/5SdxIKHl',
                    start: '2022-03-17T12:00:00.000Z',
                    subscribed: true,
                    url: 'https://trello.com/c/5SdxIKHl/302-card-6',
                    cover: [Array],
                    isTemplate: false,
                    cardRole: null
                }
            ]
        }
    },
];

test.each(cases)("", async (unitCase) => {
    let response = await module.filterCards({cardArray: unitCase["cardArray"], cardProperties: unitCase["cardProperties"]});
    await expect(
        response
    ).toEqual(
        unitCase["return"]
    );
});

    // {
    //     "cardArray": testData,
    //     "cardProperties": ["name"],
    //     "return": {
    //         statusText: 'OK',
    //         data: [
    //             { name: 'Card 1' },
    //             { name: 'Card 2' },
    //             { name: 'Card 3' },
    //             { name: 'Card 4' },
    //             { name: 'Card 5' },
    //             { name: 'Card 6' }
    //         ]
    //     }
    // },
    // {
    //     "cardArray": testData,
    //     "cardProperties": ["name", "id"],
    //     "return": {
    //         statusText: 'OK',
    //         data: [
    //             { name: 'Card 1', id: '60fa41555c017a81ce406486' },
    //             { name: 'Card 2', id: '612bfeb4d3b75f6f89c7b20a' },
    //             { name: 'Card 3', id: '60fd985ffdce8910d6723cb0' },
    //             { name: 'Card 4', id: '6137c28da3e07f6ba07ff01e' },
    //             { name: 'Card 5', id: '6216813334e8d64b77e547d2' },
    //             { name: 'Card 6', id: '621e7d1ef9b99e634a6a5853' }
    //         ]
    //     }